배송 정보에 한글로 이루어진 식별자를 만들어 줍니다.
gdsc-ssu/ssung-delivery-back pull request #23
Opened 2023-03-21 08:25 UTC by citrusinesis

Shipment에 한글로 이루어진 3*3 형태의 식별자를 생성해 줍니다. (Ex 기분이.슝슝한.서울대)

2023-03-21 08:31 UTC, citrusinesis commented on domain/shipment/shipment_service.py
> +    result = globals()[res.value]
Reflection 이용해서 Schema 생성할 수 있도록 만들어놨습니다. 런타임 에러가 날까 굉장히 무섭긴 하네요 ㅋㅋㅋㅋ

2023-03-21 15:38 UTC, citrusinesis commented on domain/shipment/shipment_service.py
> +    result = globals()[res.value]
@Think-JIn99

2023-03-23 13:05 UTC, Think-JIn99 requested changes

2023-03-23 13:05 UTC, thinkjin99 commented on domain/common/identifier.py
> +    if query:
여기있는 중복처리 로직 구조를 좀 변경하고 싶네요. 지금 보면 배송 생성 -> 식별자 생성 -> 중복 조회의 루틴으로 가는데 중복이 그렇게 자주 발생할 것 같지도 않아 보여서... 차라리 create_shipment에서 예외 처리를 통해 예외가 발생했을 경우에만 함수 다시 실행하는 구조로 가는게 나을것 같습니다. 이렇게 하면 항상 중복 처리를 위해 쿼리 한번 씩 더 날리는 문제도 해결하고 좀 더 구조가 깔끔할 것 같은데용. (무조건 중복 체크 쿼리 전송 -> 해봤는데 중복일 경우 배송 생성 프로세스 재시도) 로 변경하고 싶어요

2023-03-23 13:05 UTC, thinkjin99 commented on domain/shipment/shipment_service.py
> +    result = globals()[res.value]
결국 전역변수로 선언된 어떤 변수 값을 동적으로 읽는게 목적인 거 잖아요? 이렇게 하는 것보단 차라리 못생겨도 if같이 명확한 형태로 빼는게 좋을 것 같아요. 아이디어도 좋고 솔직히 유지보수도 쉬운 편일거 같긴 하지만!  코드가 너무나도 간결해 직관적이지 않습니다. 차라리 모델 딕셔너리를 만들고 거기서 키를 통해 조회할 수 있게 하는 형태가 나을 것 같아요. {"ShipmentOut":ShipmentOut} 머 이르케..

2023-03-23 13:05 UTC, thinkjin99 commented on domain/common/identifier.py
> +    return id
요기서 만든 id를 모델에서 default 값으로 쉽먼트 생성할 때 들어가게 처리해주실 수 있나요?

2023-03-24 02:56 UTC, merged